-- AlterTable
ALTER TABLE `milestone` ADD COLUMN `cancellation_reason` MEDIUMTEXT NULL,
    ADD COLUMN `cancellation_requested_at` DATETIME(3) NULL,
    ADD COLUMN `cancellation_responded_at` DATETIME(3) NULL,
    ADD COLUMN `cancellation_status` ENUM('PENDING', 'ACCEPTED', 'DECLINED') NULL;

-- AlterTable
ALTER TABLE `notification` MODIFY `event` ENUM('JOB_INVITATION_CREATED', 'JOB_INVITATION_CANCELLED', 'JOB_INVITATION_ACCEPTED', 'JOB_INVITATION_DECLINED', 'JOB_HIRE', 'JOB_ACCEPT', 'JOB_OFFER_SENT', 'JOB_OFFER_UPDATED', 'JOB_OFFER_WITHDRAWN', 'JOB_OFFER_DECLINED', 'PROPOSAL_SUBMITTED', 'CONTRACT_MILESTONE_CREATED', 'CONTRACT_MILESTONE_SUBMITTED', 'CONTRACT_MILESTONE_APPROVED', 'CONTRACT_MILESTONE_DECLINED', 'CONTRACT_MILESTONE_CANCELLATION_REQUESTED', 'DISPUTE_CREATED', 'DISPUTE_UPDATED', 'SYSTEM_MESSAGE') NOT NULL;

-- CreateIndex
CREATE INDEX `idx_milestone_cancellation_status` ON `Milestone`(`cancellation_status`);
