-- AlterTable
ALTER TABLE `notification` MODIFY `category` ENUM('JOB', 'PROPOSAL', 'CONTRACT', 'DISPUTE', 'SYSTEM') NOT NULL,
    MODIFY `event` ENUM('JOB_INVITATION_CREATED', 'JOB_INVITATION_CANCELLED', 'JOB_INVITATION_ACCEPTED', 'JOB_INVITATION_DECLINED', 'JOB_HIRE', 'JOB_ACCEPT', 'JOB_OFFER_SENT', 'JOB_OFFER_UPDATED', 'JOB_OFFER_WITHDRAWN', 'JOB_OFFER_DECLINED', 'PROPOSAL_SUBMITTED', 'CONTRACT_MILESTONE_CREATED', 'CONTRACT_MILESTONE_SUBMITTED', 'CONTRACT_MILESTONE_APPROVED', 'CONTRACT_MILESTONE_DECLINED', 'DISPUTE_CREATED', 'DISPUTE_UPDATED', 'SYSTEM_MESSAGE') NOT NULL,
    MODIFY `resource_type` ENUM('JOB_POST', 'JOB_INVITATION', 'JOB_PROPOSAL', 'JOB_OFFER', 'CONTRACT', 'CONTRACT_MILESTONE', 'MILESTONE_SUBMISSION', 'DISPUTE', 'SYSTEM') NULL;
