-- AlterTable
ALTER TABLE `notification` MODIFY `event` ENUM('JOB_INVITATION_CREATED', 'JOB_INVITATION_CANCELLED', 'JOB_INVITATION_ACCEPTED', 'JOB_INVITATION_DECLINED', 'JOB_HIRE', 'JOB_ACCEPT', 'JOB_OFFER_SENT', 'PROPOSAL_SUBMITTED', 'DISPUTE_CREATED', 'DISPUTE_UPDATED', 'SYSTEM_MESSAGE') NOT NULL,
    MODIFY `resource_type` ENUM('JOB_POST', 'JOB_INVITATION', 'JOB_PROPOSAL', 'JOB_OFFER', 'CONTRACT', 'DISPUTE', 'SYSTEM') NULL;
