-- AlterTable
ALTER TABLE `dispute` MODIFY `status` ENUM('OPEN', 'NEGOTIATION', 'INTERNAL_MEDIATION', 'AWAITING_ARBITRATION_FEES', 'ARBITRATION_READY', 'ARBITRATION', 'RESOLVED_RELEASE_ALL', 'RESOLVED_REFUND_ALL', 'RESOLVED_SPLIT', 'CANCELED', 'EXPIRED', 'CLOSED_FOR_EXTERNAL_RESOLUTION') NOT NULL DEFAULT 'OPEN';
