-- AlterTable
ALTER TABLE `match_interaction` MODIFY `type` ENUM('JOB_VIEW', 'PROFILE_VIEW', 'PROPOSAL_SUBMITTED', 'PROPOSAL_SHORTLISTED', 'PROPOSAL_DECLINED', 'PROPOSAL_INTERVIEWING', 'PROPOSAL_HIRED', 'INVITATION_SENT', 'INVITATION_ACCEPTED', 'INVITATION_DECLINED', 'OFFER_SENT', 'OFFER_ACCEPTED', 'OFFER_DECLINED') NOT NULL;
