-- AlterTable
ALTER TABLE `notification` MODIFY `event` ENUM('JOB_INVITATION_CREATED', 'JOB_INVITATION_CANCELLED', 'JOB_INVITATION_ACCEPTED', 'JOB_INVITATION_DECLINED', 'JOB_HIRE', 'JOB_ACCEPT', 'JOB_OFFER_SENT', 'JOB_OFFER_UPDATED', 'JOB_OFFER_WITHDRAWN', 'JOB_OFFER_DECLINED', 'PROPOSAL_SUBMITTED', 'DISPUTE_CREATED', 'DISPUTE_UPDATED', 'SYSTEM_MESSAGE') NOT NULL;
