// Additional skills for ML diverse data - 150+ new skills
export const ADDITIONAL_SKILLS = [
  // ============================================================================
  // FRONTEND FRAMEWORKS & LIBRARIES (30 skills)
  // ============================================================================
  { id: 'skill_solidjs', slug: 'solidjs', name: 'SolidJS', description: 'Reactive UI library with fine-grained reactivity.' },
  { id: 'skill_qwik', slug: 'qwik', name: 'Qwik', description: 'Resumable framework for instant-loading web apps.' },
  { id: 'skill_preact', slug: 'preact', name: 'Preact', description: 'Fast 3kB alternative to React with the same API.' },
  { id: 'skill_alpinejs', slug: 'alpinejs', name: 'Alpine.js', description: 'Lightweight JavaScript framework for composing behavior.' },
  { id: 'skill_htmx', slug: 'htmx', name: 'HTMX', description: 'High power tools for HTML without JavaScript.' },
  { id: 'skill_lit', slug: 'lit', name: 'Lit', description: 'Simple library for building fast web components.' },
  { id: 'skill_stimulus', slug: 'stimulus', name: 'Stimulus', description: 'Modest JavaScript framework for HTML you already have.' },
  { id: 'skill_mithril', slug: 'mithril', name: 'Mithril.js', description: 'Modern client-side JavaScript framework.' },
  { id: 'skill_ember', slug: 'ember', name: 'Ember.js', description: 'Framework for ambitious web developers.' },
  { id: 'skill_backbone', slug: 'backbone', name: 'Backbone.js', description: 'Give structure to web applications.' },
  { id: 'skill_chakra_ui', slug: 'chakra-ui', name: 'Chakra UI', description: 'Simple, modular React component library.' },
  { id: 'skill_material_ui', slug: 'material-ui', name: 'Material UI', description: 'React components implementing Material Design.' },
  { id: 'skill_ant_design', slug: 'ant-design', name: 'Ant Design', description: 'Enterprise-class UI design language for React.' },
  { id: 'skill_radix_ui', slug: 'radix-ui', name: 'Radix UI', description: 'Unstyled, accessible React components.' },
  { id: 'skill_headless_ui', slug: 'headless-ui', name: 'Headless UI', description: 'Unstyled, accessible UI components for Tailwind.' },
  { id: 'skill_shadcn', slug: 'shadcn-ui', name: 'shadcn/ui', description: 'Re-usable components built with Radix and Tailwind.' },
  { id: 'skill_framer_motion', slug: 'framer-motion', name: 'Framer Motion', description: 'Production-ready motion library for React.' },
  { id: 'skill_gsap', slug: 'gsap', name: 'GSAP', description: 'Professional-grade animation for the modern web.' },
  { id: 'skill_threejs', slug: 'threejs', name: 'Three.js', description: '3D library for creating WebGL content.' },
  { id: 'skill_d3js', slug: 'd3js', name: 'D3.js', description: 'Data-driven documents for visualization.' },
  { id: 'skill_chartjs', slug: 'chartjs', name: 'Chart.js', description: 'Simple yet flexible JavaScript charting.' },
  { id: 'skill_echarts', slug: 'echarts', name: 'ECharts', description: 'Powerful charting and visualization library.' },
  { id: 'skill_highcharts', slug: 'highcharts', name: 'Highcharts', description: 'Interactive JavaScript charts for web pages.' },
  { id: 'skill_recharts', slug: 'recharts', name: 'Recharts', description: 'Composable charting library for React.' },
  { id: 'skill_visx', slug: 'visx', name: 'visx', description: 'Collection of low-level visualization primitives.' },
  { id: 'skill_mobx', slug: 'mobx', name: 'MobX', description: 'Simple, scalable state management.' },
  { id: 'skill_recoil', slug: 'recoil', name: 'Recoil', description: 'State management library for React.' },
  { id: 'skill_jotai', slug: 'jotai', name: 'Jotai', description: 'Primitive and flexible state management.' },
  { id: 'skill_xstate', slug: 'xstate', name: 'XState', description: 'State machines and statecharts for JavaScript.' },
  { id: 'skill_rxjs', slug: 'rxjs', name: 'RxJS', description: 'Reactive Extensions Library for JavaScript.' },

  // ============================================================================
  // BACKEND FRAMEWORKS & RUNTIME (30 skills)
  // ============================================================================
  { id: 'skill_hono', slug: 'hono', name: 'Hono', description: 'Ultrafast web framework for the Edge.' },
  { id: 'skill_elysia', slug: 'elysia', name: 'Elysia', description: 'Ergonomic framework for building backend servers.' },
  { id: 'skill_trpc', slug: 'trpc', name: 'tRPC', description: 'End-to-end typesafe APIs made easy.' },
  { id: 'skill_grpc', slug: 'grpc', name: 'gRPC', description: 'High performance RPC framework.' },
  { id: 'skill_flask', slug: 'flask', name: 'Flask', description: 'Lightweight WSGI web application framework.' },
  { id: 'skill_gin', slug: 'gin', name: 'Gin', description: 'HTTP web framework written in Go.' },
  { id: 'skill_echo', slug: 'echo', name: 'Echo', description: 'High performance Go web framework.' },
  { id: 'skill_fiber', slug: 'fiber', name: 'Fiber', description: 'Express-inspired web framework for Go.' },
  { id: 'skill_chi', slug: 'chi', name: 'Chi', description: 'Lightweight, idiomatic router for Go.' },
  { id: 'skill_actix', slug: 'actix', name: 'Actix Web', description: 'Powerful, pragmatic Rust web framework.' },
  { id: 'skill_axum', slug: 'axum', name: 'Axum', description: 'Ergonomic and modular Rust web framework.' },
  { id: 'skill_rocket', slug: 'rocket', name: 'Rocket', description: 'Web framework for Rust with focus on ease.' },
  { id: 'skill_phoenix', slug: 'phoenix', name: 'Phoenix', description: 'Productive web framework for Elixir.' },
  { id: 'skill_elixir', slug: 'elixir', name: 'Elixir', description: 'Dynamic, functional language for scalable apps.' },
  { id: 'skill_erlang', slug: 'erlang', name: 'Erlang', description: 'Language for building concurrent systems.' },
  { id: 'skill_scala', slug: 'scala', name: 'Scala', description: 'Object-functional programming language.' },
  { id: 'skill_akka', slug: 'akka', name: 'Akka', description: 'Toolkit for building concurrent applications.' },
  { id: 'skill_play', slug: 'play-framework', name: 'Play Framework', description: 'High velocity web framework for Java and Scala.' },
  { id: 'skill_quarkus', slug: 'quarkus', name: 'Quarkus', description: 'Kubernetes-native Java framework.' },
  { id: 'skill_micronaut', slug: 'micronaut', name: 'Micronaut', description: 'Modern JVM-based full-stack framework.' },
  { id: 'skill_ktor', slug: 'ktor', name: 'Ktor', description: 'Asynchronous framework for Kotlin.' },
  { id: 'skill_deno', slug: 'deno', name: 'Deno', description: 'Secure runtime for JavaScript and TypeScript.' },
  { id: 'skill_bun', slug: 'bun', name: 'Bun', description: 'Fast all-in-one JavaScript runtime.' },
  { id: 'skill_dotnet', slug: 'dotnet', name: '.NET Core', description: 'Cross-platform framework from Microsoft.' },
  { id: 'skill_aspnet', slug: 'aspnet', name: 'ASP.NET', description: 'Framework for building web apps with .NET.' },
  { id: 'skill_blazor', slug: 'blazor', name: 'Blazor', description: 'Build interactive web UIs with C#.' },
  { id: 'skill_symfony', slug: 'symfony', name: 'Symfony', description: 'PHP framework for web applications.' },
  { id: 'skill_codeigniter', slug: 'codeigniter', name: 'CodeIgniter', description: 'Powerful PHP framework with small footprint.' },
  { id: 'skill_yii', slug: 'yii', name: 'Yii Framework', description: 'High-performance PHP framework.' },
  { id: 'skill_adonisjs', slug: 'adonisjs', name: 'AdonisJS', description: 'TypeScript-first web framework for Node.js.' },

  // ============================================================================
  // DATABASES & DATA STORES (25 skills)
  // ============================================================================
  { id: 'skill_sqlite', slug: 'sqlite', name: 'SQLite', description: 'Self-contained SQL database engine.' },
  { id: 'skill_cockroachdb', slug: 'cockroachdb', name: 'CockroachDB', description: 'Distributed SQL database for cloud apps.' },
  { id: 'skill_planetscale', slug: 'planetscale', name: 'PlanetScale', description: 'Serverless MySQL platform.' },
  { id: 'skill_supabase', slug: 'supabase', name: 'Supabase', description: 'Open source Firebase alternative.' },
  { id: 'skill_neon', slug: 'neon', name: 'Neon', description: 'Serverless Postgres with branching.' },
  { id: 'skill_turso', slug: 'turso', name: 'Turso', description: 'Edge-hosted distributed database.' },
  { id: 'skill_neo4j', slug: 'neo4j', name: 'Neo4j', description: 'Graph database management system.' },
  { id: 'skill_dgraph', slug: 'dgraph', name: 'Dgraph', description: 'Native GraphQL database.' },
  { id: 'skill_arangodb', slug: 'arangodb', name: 'ArangoDB', description: 'Multi-model database for graphs and documents.' },
  { id: 'skill_couchdb', slug: 'couchdb', name: 'CouchDB', description: 'Document-oriented NoSQL database.' },
  { id: 'skill_rethinkdb', slug: 'rethinkdb', name: 'RethinkDB', description: 'Real-time database for web apps.' },
  { id: 'skill_timescaledb', slug: 'timescaledb', name: 'TimescaleDB', description: 'Time-series database on PostgreSQL.' },
  { id: 'skill_influxdb', slug: 'influxdb', name: 'InfluxDB', description: 'Time series database platform.' },
  { id: 'skill_clickhouse', slug: 'clickhouse', name: 'ClickHouse', description: 'Column-oriented OLAP database.' },
  { id: 'skill_druid', slug: 'druid', name: 'Apache Druid', description: 'Real-time analytics database.' },
  { id: 'skill_pinecone', slug: 'pinecone', name: 'Pinecone', description: 'Vector database for ML applications.' },
  { id: 'skill_weaviate', slug: 'weaviate', name: 'Weaviate', description: 'Vector search engine and database.' },
  { id: 'skill_milvus', slug: 'milvus', name: 'Milvus', description: 'Open-source vector database.' },
  { id: 'skill_qdrant', slug: 'qdrant', name: 'Qdrant', description: 'Vector similarity search engine.' },
  { id: 'skill_chroma', slug: 'chroma', name: 'Chroma', description: 'AI-native embedding database.' },
  { id: 'skill_memcached', slug: 'memcached', name: 'Memcached', description: 'Distributed memory caching system.' },
  { id: 'skill_hazelcast', slug: 'hazelcast', name: 'Hazelcast', description: 'In-memory computing platform.' },
  { id: 'skill_etcd', slug: 'etcd', name: 'etcd', description: 'Distributed key-value store.' },
  { id: 'skill_consul', slug: 'consul', name: 'Consul', description: 'Service mesh and key-value store.' },
  { id: 'skill_foundationdb', slug: 'foundationdb', name: 'FoundationDB', description: 'Distributed database for mixed workloads.' },

  // ============================================================================
  // DEVOPS & CLOUD PLATFORMS (30 skills)
  // ============================================================================
  { id: 'skill_cloudflare', slug: 'cloudflare', name: 'Cloudflare', description: 'Global cloud platform for security and performance.' },
  { id: 'skill_vercel', slug: 'vercel', name: 'Vercel', description: 'Platform for frontend frameworks and static sites.' },
  { id: 'skill_netlify', slug: 'netlify', name: 'Netlify', description: 'Platform for web projects automation.' },
  { id: 'skill_railway', slug: 'railway', name: 'Railway', description: 'Infrastructure platform for deployment.' },
  { id: 'skill_render', slug: 'render', name: 'Render', description: 'Unified cloud to build and run apps.' },
  { id: 'skill_flyio', slug: 'fly-io', name: 'Fly.io', description: 'Platform for running apps close to users.' },
  { id: 'skill_digitalocean', slug: 'digitalocean', name: 'DigitalOcean', description: 'Cloud infrastructure provider.' },
  { id: 'skill_linode', slug: 'linode', name: 'Linode', description: 'Cloud computing and hosting.' },
  { id: 'skill_vultr', slug: 'vultr', name: 'Vultr', description: 'Cloud compute platform.' },
  { id: 'skill_hetzner', slug: 'hetzner', name: 'Hetzner', description: 'European cloud and hosting provider.' },
  { id: 'skill_istio', slug: 'istio', name: 'Istio', description: 'Service mesh for Kubernetes.' },
  { id: 'skill_linkerd', slug: 'linkerd', name: 'Linkerd', description: 'Ultralight service mesh for Kubernetes.' },
  { id: 'skill_envoy', slug: 'envoy', name: 'Envoy', description: 'Cloud-native high-performance proxy.' },
  { id: 'skill_traefik', slug: 'traefik', name: 'Traefik', description: 'Cloud-native application proxy.' },
  { id: 'skill_vault', slug: 'vault', name: 'HashiCorp Vault', description: 'Secrets management and data protection.' },
  { id: 'skill_nomad', slug: 'nomad', name: 'HashiCorp Nomad', description: 'Workload orchestrator.' },
  { id: 'skill_packer', slug: 'packer', name: 'Packer', description: 'Tool for creating machine images.' },
  { id: 'skill_vagrant', slug: 'vagrant', name: 'Vagrant', description: 'Tool for building development environments.' },
  { id: 'skill_datadog', slug: 'datadog', name: 'Datadog', description: 'Monitoring and security platform.' },
  { id: 'skill_newrelic', slug: 'newrelic', name: 'New Relic', description: 'Observability platform.' },
  { id: 'skill_splunk', slug: 'splunk', name: 'Splunk', description: 'Platform for operational intelligence.' },
  { id: 'skill_elastic_stack', slug: 'elastic-stack', name: 'Elastic Stack', description: 'Search, observe, and protect your data.' },
  { id: 'skill_loki', slug: 'loki', name: 'Grafana Loki', description: 'Log aggregation system.' },
  { id: 'skill_tempo', slug: 'tempo', name: 'Grafana Tempo', description: 'Distributed tracing backend.' },
  { id: 'skill_jaeger', slug: 'jaeger', name: 'Jaeger', description: 'Distributed tracing platform.' },
  { id: 'skill_zipkin', slug: 'zipkin', name: 'Zipkin', description: 'Distributed tracing system.' },
  { id: 'skill_opentelemetry', slug: 'opentelemetry', name: 'OpenTelemetry', description: 'Observability framework.' },
  { id: 'skill_fluentd', slug: 'fluentd', name: 'Fluentd', description: 'Unified logging layer.' },
  { id: 'skill_vector', slug: 'vector', name: 'Vector', description: 'High-performance observability pipeline.' },
  { id: 'skill_crossplane', slug: 'crossplane', name: 'Crossplane', description: 'Cloud native control planes.' },

  // ============================================================================
  // AI/ML & DATA SCIENCE (30 skills)
  // ============================================================================
  { id: 'skill_openai_api', slug: 'openai-api', name: 'OpenAI API', description: 'API for GPT and DALL-E models.' },
  { id: 'skill_anthropic', slug: 'anthropic', name: 'Anthropic Claude', description: 'Claude AI assistant API.' },
  { id: 'skill_gemini', slug: 'gemini', name: 'Google Gemini', description: 'Google multimodal AI model.' },
  { id: 'skill_llama', slug: 'llama', name: 'LLaMA', description: 'Meta open-source language model.' },
  { id: 'skill_mistral', slug: 'mistral', name: 'Mistral AI', description: 'Open-weight language models.' },
  { id: 'skill_ollama', slug: 'ollama', name: 'Ollama', description: 'Run large language models locally.' },
  { id: 'skill_llamaindex', slug: 'llamaindex', name: 'LlamaIndex', description: 'Data framework for LLM applications.' },
  { id: 'skill_semantic_kernel', slug: 'semantic-kernel', name: 'Semantic Kernel', description: 'Microsoft SDK for AI integration.' },
  { id: 'skill_autogen', slug: 'autogen', name: 'AutoGen', description: 'Framework for multi-agent conversations.' },
  { id: 'skill_crewai', slug: 'crewai', name: 'CrewAI', description: 'Framework for orchestrating AI agents.' },
  { id: 'skill_mlflow', slug: 'mlflow', name: 'MLflow', description: 'Platform for ML lifecycle management.' },
  { id: 'skill_kubeflow', slug: 'kubeflow', name: 'Kubeflow', description: 'ML toolkit for Kubernetes.' },
  { id: 'skill_ray', slug: 'ray', name: 'Ray', description: 'Framework for scaling AI applications.' },
  { id: 'skill_dask', slug: 'dask', name: 'Dask', description: 'Parallel computing library for Python.' },
  { id: 'skill_spark', slug: 'apache-spark', name: 'Apache Spark', description: 'Unified analytics engine.' },
  { id: 'skill_databricks', slug: 'databricks', name: 'Databricks', description: 'Unified data analytics platform.' },
  { id: 'skill_snowflake', slug: 'snowflake', name: 'Snowflake', description: 'Cloud data platform.' },
  { id: 'skill_dbt', slug: 'dbt', name: 'dbt', description: 'Data transformation tool.' },
  { id: 'skill_great_expectations', slug: 'great-expectations', name: 'Great Expectations', description: 'Data validation framework.' },
  { id: 'skill_feast', slug: 'feast', name: 'Feast', description: 'Feature store for ML.' },
  { id: 'skill_weights_biases', slug: 'wandb', name: 'Weights & Biases', description: 'ML experiment tracking.' },
  { id: 'skill_neptune', slug: 'neptune', name: 'Neptune.ai', description: 'Metadata store for MLOps.' },
  { id: 'skill_comet', slug: 'comet', name: 'Comet ML', description: 'ML experiment management.' },
  { id: 'skill_bentoml', slug: 'bentoml', name: 'BentoML', description: 'ML model serving framework.' },
  { id: 'skill_seldon', slug: 'seldon', name: 'Seldon Core', description: 'ML deployment on Kubernetes.' },
  { id: 'skill_triton', slug: 'triton', name: 'NVIDIA Triton', description: 'Inference serving software.' },
  { id: 'skill_onnx', slug: 'onnx', name: 'ONNX', description: 'Open neural network exchange format.' },
  { id: 'skill_jax', slug: 'jax', name: 'JAX', description: 'High-performance numerical computing.' },
  { id: 'skill_spacy', slug: 'spacy', name: 'spaCy', description: 'Industrial-strength NLP library.' },
  { id: 'skill_nltk', slug: 'nltk', name: 'NLTK', description: 'Natural Language Toolkit for Python.' },

  // ============================================================================
  // TESTING & QUALITY (20 skills)
  // ============================================================================
  { id: 'skill_vitest', slug: 'vitest', name: 'Vitest', description: 'Blazing fast unit test framework.' },
  { id: 'skill_testing_library', slug: 'testing-library', name: 'Testing Library', description: 'Simple testing utilities.' },
  { id: 'skill_msw', slug: 'msw', name: 'MSW', description: 'Mock Service Worker for API mocking.' },
  { id: 'skill_pytest', slug: 'pytest', name: 'pytest', description: 'Python testing framework.' },
  { id: 'skill_unittest', slug: 'unittest', name: 'unittest', description: 'Python unit testing framework.' },
  { id: 'skill_mocha', slug: 'mocha', name: 'Mocha', description: 'JavaScript test framework.' },
  { id: 'skill_chai', slug: 'chai', name: 'Chai', description: 'BDD/TDD assertion library.' },
  { id: 'skill_junit', slug: 'junit', name: 'JUnit', description: 'Java testing framework.' },
  { id: 'skill_testng', slug: 'testng', name: 'TestNG', description: 'Testing framework for Java.' },
  { id: 'skill_nunit', slug: 'nunit', name: 'NUnit', description: '.NET unit testing framework.' },
  { id: 'skill_xunit', slug: 'xunit', name: 'xUnit', description: 'Free unit testing tool for .NET.' },
  { id: 'skill_k6', slug: 'k6', name: 'k6', description: 'Modern load testing tool.' },
  { id: 'skill_locust', slug: 'locust', name: 'Locust', description: 'Scalable load testing framework.' },
  { id: 'skill_gatling', slug: 'gatling', name: 'Gatling', description: 'Load testing for web applications.' },
  { id: 'skill_artillery', slug: 'artillery', name: 'Artillery', description: 'Cloud-scale load testing.' },
  { id: 'skill_appium', slug: 'appium', name: 'Appium', description: 'Mobile app automation framework.' },
  { id: 'skill_detox', slug: 'detox', name: 'Detox', description: 'E2E testing for React Native.' },
  { id: 'skill_maestro', slug: 'maestro', name: 'Maestro', description: 'Mobile UI testing framework.' },
  { id: 'skill_webdriverio', slug: 'webdriverio', name: 'WebdriverIO', description: 'Browser and mobile automation.' },
  { id: 'skill_puppeteer', slug: 'puppeteer', name: 'Puppeteer', description: 'Headless Chrome Node.js API.' },

  // ============================================================================
  // SECURITY & COMPLIANCE (20 skills)
  // ============================================================================
  { id: 'skill_owasp', slug: 'owasp', name: 'OWASP', description: 'Web application security standards.' },
  { id: 'skill_burp_suite', slug: 'burp-suite', name: 'Burp Suite', description: 'Web security testing toolkit.' },
  { id: 'skill_snyk', slug: 'snyk', name: 'Snyk', description: 'Developer security platform.' },
  { id: 'skill_sonarqube', slug: 'sonarqube', name: 'SonarQube', description: 'Code quality and security.' },
  { id: 'skill_checkmarx', slug: 'checkmarx', name: 'Checkmarx', description: 'Application security testing.' },
  { id: 'skill_veracode', slug: 'veracode', name: 'Veracode', description: 'Application security platform.' },
  { id: 'skill_oauth', slug: 'oauth', name: 'OAuth 2.0', description: 'Authorization framework.' },
  { id: 'skill_jwt', slug: 'jwt', name: 'JWT', description: 'JSON Web Tokens for authentication.' },
  { id: 'skill_keycloak', slug: 'keycloak', name: 'Keycloak', description: 'Open source identity management.' },
  { id: 'skill_auth0', slug: 'auth0', name: 'Auth0', description: 'Identity platform.' },
  { id: 'skill_okta', slug: 'okta', name: 'Okta', description: 'Identity and access management.' },
  { id: 'skill_cognito', slug: 'cognito', name: 'AWS Cognito', description: 'User identity and access.' },
  { id: 'skill_clerk', slug: 'clerk', name: 'Clerk', description: 'Authentication and user management.' },
  { id: 'skill_nextauth', slug: 'nextauth', name: 'NextAuth.js', description: 'Authentication for Next.js.' },
  { id: 'skill_passport', slug: 'passport', name: 'Passport.js', description: 'Authentication middleware for Node.js.' },
  { id: 'skill_zap', slug: 'owasp-zap', name: 'OWASP ZAP', description: 'Web app security scanner.' },
  { id: 'skill_nmap', slug: 'nmap', name: 'Nmap', description: 'Network discovery and security auditing.' },
  { id: 'skill_wireshark', slug: 'wireshark', name: 'Wireshark', description: 'Network protocol analyzer.' },
  { id: 'skill_metasploit', slug: 'metasploit', name: 'Metasploit', description: 'Penetration testing framework.' },
  { id: 'skill_kali', slug: 'kali-linux', name: 'Kali Linux', description: 'Penetration testing distribution.' },

  // ============================================================================
  // BLOCKCHAIN & WEB3 (20 skills)
  // ============================================================================
  { id: 'skill_foundry', slug: 'foundry', name: 'Foundry', description: 'Blazing fast Ethereum toolkit.' },
  { id: 'skill_wagmi', slug: 'wagmi', name: 'wagmi', description: 'React Hooks for Ethereum.' },
  { id: 'skill_rainbowkit', slug: 'rainbowkit', name: 'RainbowKit', description: 'Wallet connection for dApps.' },
  { id: 'skill_thirdweb', slug: 'thirdweb', name: 'thirdweb', description: 'Web3 development framework.' },
  { id: 'skill_alchemy', slug: 'alchemy', name: 'Alchemy', description: 'Web3 development platform.' },
  { id: 'skill_infura', slug: 'infura', name: 'Infura', description: 'Ethereum API and infrastructure.' },
  { id: 'skill_moralis', slug: 'moralis', name: 'Moralis', description: 'Web3 development platform.' },
  { id: 'skill_the_graph', slug: 'the-graph', name: 'The Graph', description: 'Indexing protocol for Web3.' },
  { id: 'skill_chainlink', slug: 'chainlink', name: 'Chainlink', description: 'Decentralized oracle network.' },
  { id: 'skill_openzeppelin', slug: 'openzeppelin', name: 'OpenZeppelin', description: 'Smart contract security.' },
  { id: 'skill_truffle', slug: 'truffle', name: 'Truffle', description: 'Ethereum development framework.' },
  { id: 'skill_brownie', slug: 'brownie', name: 'Brownie', description: 'Python framework for Ethereum.' },
  { id: 'skill_anchor', slug: 'anchor', name: 'Anchor', description: 'Solana development framework.' },
  { id: 'skill_solana', slug: 'solana', name: 'Solana', description: 'High-performance blockchain.' },
  { id: 'skill_polkadot', slug: 'polkadot', name: 'Polkadot', description: 'Multi-chain protocol.' },
  { id: 'skill_cosmos', slug: 'cosmos', name: 'Cosmos SDK', description: 'Framework for blockchain apps.' },
  { id: 'skill_near', slug: 'near', name: 'NEAR Protocol', description: 'Scalable blockchain platform.' },
  { id: 'skill_avalanche', slug: 'avalanche', name: 'Avalanche', description: 'Platform for dApps.' },
  { id: 'skill_polygon', slug: 'polygon', name: 'Polygon', description: 'Ethereum scaling solution.' },
  { id: 'skill_arbitrum', slug: 'arbitrum', name: 'Arbitrum', description: 'Ethereum Layer 2 solution.' },

  // ============================================================================
  // MOBILE & CROSS-PLATFORM (15 skills)
  // ============================================================================
  { id: 'skill_tauri', slug: 'tauri', name: 'Tauri', description: 'Build smaller, faster desktop apps.' },
  { id: 'skill_electron', slug: 'electron', name: 'Electron', description: 'Build cross-platform desktop apps.' },
  { id: 'skill_nwjs', slug: 'nwjs', name: 'NW.js', description: 'Build desktop apps with web tech.' },
  { id: 'skill_pwa', slug: 'pwa', name: 'Progressive Web Apps', description: 'Web apps with native features.' },
  { id: 'skill_cordova', slug: 'cordova', name: 'Apache Cordova', description: 'Mobile apps with HTML/CSS/JS.' },
  { id: 'skill_nativescript', slug: 'nativescript', name: 'NativeScript', description: 'Native mobile apps with JS.' },
  { id: 'skill_maui', slug: 'maui', name: '.NET MAUI', description: 'Cross-platform app UI.' },
  { id: 'skill_compose_multiplatform', slug: 'compose-multiplatform', name: 'Compose Multiplatform', description: 'Declarative UI for multiple platforms.' },
  { id: 'skill_kmm', slug: 'kmm', name: 'Kotlin Multiplatform', description: 'Share code across platforms.' },
  { id: 'skill_objective_c', slug: 'objective-c', name: 'Objective-C', description: 'Programming language for Apple.' },
  { id: 'skill_core_data', slug: 'core-data', name: 'Core Data', description: 'Apple data persistence framework.' },
  { id: 'skill_room', slug: 'room', name: 'Room', description: 'Android persistence library.' },
  { id: 'skill_retrofit', slug: 'retrofit', name: 'Retrofit', description: 'Type-safe HTTP client for Android.' },
  { id: 'skill_alamofire', slug: 'alamofire', name: 'Alamofire', description: 'HTTP networking library for Swift.' },
  { id: 'skill_combine', slug: 'combine', name: 'Combine', description: 'Apple reactive framework.' },
]


// ============================================================================
// ADDITIONAL SKILLS FOR FREELANCER TEMPLATES (to ensure all skills exist)
// ============================================================================
export const EXTRA_SKILLS_FOR_TEMPLATES = [
  // Frontend state & tools
  { id: 'skill_pinia', slug: 'pinia', name: 'Pinia', description: 'Vue.js state management.' },
  { id: 'skill_ngrx', slug: 'ngrx', name: 'NgRx', description: 'Reactive state for Angular.' },
  { id: 'skill_jasmine', slug: 'jasmine', name: 'Jasmine', description: 'BDD testing framework.' },
  { id: 'skill_karma', slug: 'karma', name: 'Karma', description: 'Test runner for JavaScript.' },
  { id: 'skill_sveltekit', slug: 'sveltekit', name: 'SvelteKit', description: 'Full-stack Svelte framework.' },
  { id: 'skill_workbox', slug: 'workbox', name: 'Workbox', description: 'Service worker libraries.' },
  { id: 'skill_lighthouse', slug: 'lighthouse', name: 'Lighthouse', description: 'Web performance auditing.' },
  { id: 'skill_stitches', slug: 'stitches', name: 'Stitches', description: 'CSS-in-JS with near-zero runtime.' },
  { id: 'skill_chromatic', slug: 'chromatic', name: 'Chromatic', description: 'Visual testing for Storybook.' },
  { id: 'skill_module_federation', slug: 'module-federation', name: 'Module Federation', description: 'Webpack micro-frontend architecture.' },
  { id: 'skill_single_spa', slug: 'single-spa', name: 'single-spa', description: 'Micro-frontend framework.' },
  { id: 'skill_lerna', slug: 'lerna', name: 'Lerna', description: 'Monorepo management tool.' },
  { id: 'skill_lottie', slug: 'lottie', name: 'Lottie', description: 'Animation library for web.' },
  { id: 'skill_rive', slug: 'rive', name: 'Rive', description: 'Interactive animations.' },
  { id: 'skill_eleventy', slug: 'eleventy', name: 'Eleventy', description: 'Simple static site generator.' },
  { id: 'skill_esbuild', slug: 'esbuild', name: 'esbuild', description: 'Extremely fast bundler.' },
  { id: 'skill_turbopack', slug: 'turbopack', name: 'Turbopack', description: 'Rust-powered bundler.' },
  { id: 'skill_axe', slug: 'axe', name: 'axe', description: 'Accessibility testing engine.' },

  // Backend tools
  { id: 'skill_celery', slug: 'celery', name: 'Celery', description: 'Distributed task queue.' },
  { id: 'skill_sqlalchemy', slug: 'sqlalchemy', name: 'SQLAlchemy', description: 'Python SQL toolkit.' },
  { id: 'skill_alembic', slug: 'alembic', name: 'Alembic', description: 'Database migrations for SQLAlchemy.' },
  { id: 'skill_gorm', slug: 'gorm', name: 'GORM', description: 'Go ORM library.' },
  { id: 'skill_nats', slug: 'nats', name: 'NATS', description: 'Cloud native messaging system.' },
  { id: 'skill_apollo', slug: 'apollo', name: 'Apollo GraphQL', description: 'GraphQL implementation.' },
  { id: 'skill_hasura', slug: 'hasura', name: 'Hasura', description: 'Instant GraphQL APIs.' },
  { id: 'skill_dataloader', slug: 'dataloader', name: 'DataLoader', description: 'Batching and caching utility.' },
  { id: 'skill_hibernate', slug: 'hibernate', name: 'Hibernate', description: 'Java ORM framework.' },
  { id: 'skill_channels', slug: 'django-channels', name: 'Django Channels', description: 'WebSocket support for Django.' },
  { id: 'skill_gunicorn', slug: 'gunicorn', name: 'Gunicorn', description: 'Python WSGI HTTP Server.' },
  { id: 'skill_eventstore', slug: 'eventstore', name: 'EventStore', description: 'Event sourcing database.' },
  { id: 'skill_debezium', slug: 'debezium', name: 'Debezium', description: 'Change data capture platform.' },
  { id: 'skill_tokio', slug: 'tokio', name: 'Tokio', description: 'Async runtime for Rust.' },
  { id: 'skill_serde', slug: 'serde', name: 'Serde', description: 'Rust serialization framework.' },
  { id: 'skill_diesel', slug: 'diesel', name: 'Diesel', description: 'Rust ORM and query builder.' },
  { id: 'skill_lambda', slug: 'aws-lambda', name: 'AWS Lambda', description: 'Serverless compute service.' },
  { id: 'skill_sqs', slug: 'aws-sqs', name: 'AWS SQS', description: 'Message queuing service.' },
  { id: 'skill_step_functions', slug: 'step-functions', name: 'Step Functions', description: 'AWS workflow orchestration.' },
  { id: 'skill_socketio', slug: 'socketio', name: 'Socket.IO', description: 'Real-time bidirectional communication.' },
  { id: 'skill_pusher', slug: 'pusher', name: 'Pusher', description: 'Real-time messaging API.' },
  { id: 'skill_ably', slug: 'ably', name: 'Ably', description: 'Real-time messaging platform.' },
  { id: 'skill_livewire', slug: 'livewire', name: 'Livewire', description: 'Full-stack Laravel framework.' },
  { id: 'skill_inertia', slug: 'inertia', name: 'Inertia.js', description: 'Modern monolith approach.' },
  { id: 'skill_horizon', slug: 'horizon', name: 'Laravel Horizon', description: 'Queue monitoring dashboard.' },
  { id: 'skill_vapor', slug: 'vapor', name: 'Laravel Vapor', description: 'Serverless Laravel deployment.' },
  { id: 'skill_ecto', slug: 'ecto', name: 'Ecto', description: 'Elixir database wrapper.' },
  { id: 'skill_otp', slug: 'otp', name: 'OTP', description: 'Erlang/Elixir concurrency framework.' },
  { id: 'skill_liveview', slug: 'liveview', name: 'Phoenix LiveView', description: 'Real-time server-rendered HTML.' },

  // Fullstack tools
  { id: 'skill_mongoose', slug: 'mongoose', name: 'Mongoose', description: 'MongoDB object modeling.' },
  { id: 'skill_uploadthing', slug: 'uploadthing', name: 'UploadThing', description: 'File uploads for Next.js.' },
  { id: 'skill_drizzle', slug: 'drizzle', name: 'Drizzle ORM', description: 'TypeScript ORM.' },
  { id: 'skill_zod', slug: 'zod', name: 'Zod', description: 'TypeScript-first schema validation.' },
  { id: 'skill_drf', slug: 'drf', name: 'Django REST Framework', description: 'Web APIs for Django.' },
  { id: 'skill_resend', slug: 'resend', name: 'Resend', description: 'Email API for developers.' },
  { id: 'skill_inngest', slug: 'inngest', name: 'Inngest', description: 'Event-driven background jobs.' },
  { id: 'skill_medusa', slug: 'medusa', name: 'Medusa', description: 'Open-source Shopify alternative.' },
  { id: 'skill_saleor', slug: 'saleor', name: 'Saleor', description: 'GraphQL-first e-commerce.' },
  { id: 'skill_algolia', slug: 'algolia', name: 'Algolia', description: 'Search and discovery API.' },

  // Mobile tools
  { id: 'skill_riverpod', slug: 'riverpod', name: 'Riverpod', description: 'Flutter state management.' },
  { id: 'skill_bloc', slug: 'bloc', name: 'BLoC', description: 'Flutter business logic component.' },
  { id: 'skill_hive', slug: 'hive', name: 'Hive', description: 'Lightweight Flutter database.' },
  { id: 'skill_reanimated', slug: 'reanimated', name: 'Reanimated', description: 'React Native animations.' },
  { id: 'skill_mmkv', slug: 'mmkv', name: 'MMKV', description: 'Fast key-value storage.' },
  { id: 'skill_flashlist', slug: 'flashlist', name: 'FlashList', description: 'Fast React Native list.' },
  { id: 'skill_swift_concurrency', slug: 'swift-concurrency', name: 'Swift Concurrency', description: 'Async/await for Swift.' },
  { id: 'skill_xctest', slug: 'xctest', name: 'XCTest', description: 'Apple testing framework.' },
  { id: 'skill_kotlin_coroutines', slug: 'kotlin-coroutines', name: 'Kotlin Coroutines', description: 'Asynchronous programming.' },
  { id: 'skill_hilt', slug: 'hilt', name: 'Hilt', description: 'Android dependency injection.' },
  { id: 'skill_fastlane', slug: 'fastlane', name: 'Fastlane', description: 'Mobile app automation.' },
  { id: 'skill_bitrise', slug: 'bitrise', name: 'Bitrise', description: 'Mobile CI/CD platform.' },
  { id: 'skill_codemagic', slug: 'codemagic', name: 'Codemagic', description: 'CI/CD for mobile apps.' },
  { id: 'skill_firebase_distribution', slug: 'firebase-distribution', name: 'Firebase App Distribution', description: 'Beta app distribution.' },

  // DevOps tools
  { id: 'skill_kustomize', slug: 'kustomize', name: 'Kustomize', description: 'Kubernetes configuration management.' },
  { id: 'skill_cdk', slug: 'aws-cdk', name: 'AWS CDK', description: 'Cloud Development Kit.' },
  { id: 'skill_sam', slug: 'aws-sam', name: 'AWS SAM', description: 'Serverless Application Model.' },
  { id: 'skill_cloudformation', slug: 'cloudformation', name: 'CloudFormation', description: 'AWS infrastructure as code.' },
  { id: 'skill_pagerduty', slug: 'pagerduty', name: 'PagerDuty', description: 'Incident management platform.' },
  { id: 'skill_runbook', slug: 'runbook', name: 'Runbook Automation', description: 'Operational procedures automation.' },
  { id: 'skill_chaos_engineering', slug: 'chaos-engineering', name: 'Chaos Engineering', description: 'System resilience testing.' },
  { id: 'skill_cdktf', slug: 'cdktf', name: 'CDK for Terraform', description: 'Terraform with programming languages.' },
  { id: 'skill_atlantis', slug: 'atlantis', name: 'Atlantis', description: 'Terraform pull request automation.' },
  { id: 'skill_spacelift', slug: 'spacelift', name: 'Spacelift', description: 'Infrastructure management platform.' },
  { id: 'skill_flux', slug: 'flux', name: 'Flux', description: 'GitOps for Kubernetes.' },
  { id: 'skill_tekton', slug: 'tekton', name: 'Tekton', description: 'Cloud-native CI/CD.' },
  { id: 'skill_dagger', slug: 'dagger', name: 'Dagger', description: 'Portable CI/CD pipelines.' },
  { id: 'skill_cilium', slug: 'cilium', name: 'Cilium', description: 'eBPF-based networking.' },
  { id: 'skill_ebpf', slug: 'ebpf', name: 'eBPF', description: 'Extended Berkeley Packet Filter.' },

  // ML/AI tools
  { id: 'skill_dagster', slug: 'dagster', name: 'Dagster', description: 'Data orchestration platform.' },
  { id: 'skill_prefect', slug: 'prefect', name: 'Prefect', description: 'Workflow orchestration.' },
  { id: 'skill_lightning', slug: 'pytorch-lightning', name: 'PyTorch Lightning', description: 'Deep learning framework.' },
  { id: 'skill_hydra', slug: 'hydra', name: 'Hydra', description: 'Configuration management for ML.' },
  { id: 'skill_yolo', slug: 'yolo', name: 'YOLO', description: 'Real-time object detection.' },
  { id: 'skill_detectron', slug: 'detectron2', name: 'Detectron2', description: 'Facebook object detection.' },
  { id: 'skill_mmdetection', slug: 'mmdetection', name: 'MMDetection', description: 'OpenMMLab detection toolbox.' },
  { id: 'skill_albumentations', slug: 'albumentations', name: 'Albumentations', description: 'Image augmentation library.' },
  { id: 'skill_chromadb', slug: 'chromadb', name: 'ChromaDB', description: 'AI-native embedding database.' },
  { id: 'skill_pgvector', slug: 'pgvector', name: 'pgvector', description: 'Vector similarity for Postgres.' },
  { id: 'skill_looker', slug: 'looker', name: 'Looker', description: 'Business intelligence platform.' },
  { id: 'skill_metabase', slug: 'metabase', name: 'Metabase', description: 'Open source BI tool.' },

  // Blockchain tools
  { id: 'skill_slither', slug: 'slither', name: 'Slither', description: 'Solidity static analyzer.' },
  { id: 'skill_mythril', slug: 'mythril', name: 'Mythril', description: 'Smart contract security analyzer.' },
  { id: 'skill_echidna', slug: 'echidna', name: 'Echidna', description: 'Ethereum smart contract fuzzer.' },
  { id: 'skill_uniswap', slug: 'uniswap', name: 'Uniswap', description: 'Decentralized exchange protocol.' },
  { id: 'skill_viem', slug: 'viem', name: 'viem', description: 'TypeScript Ethereum library.' },
  { id: 'skill_ipfs', slug: 'ipfs', name: 'IPFS', description: 'InterPlanetary File System.' },
  { id: 'skill_opensea', slug: 'opensea', name: 'OpenSea API', description: 'NFT marketplace integration.' },
  { id: 'skill_metaplex', slug: 'metaplex', name: 'Metaplex', description: 'Solana NFT standard.' },
  { id: 'skill_phantom', slug: 'phantom', name: 'Phantom', description: 'Solana wallet integration.' },
  { id: 'skill_layerzero', slug: 'layerzero', name: 'LayerZero', description: 'Omnichain interoperability.' },
  { id: 'skill_wormhole', slug: 'wormhole', name: 'Wormhole', description: 'Cross-chain messaging.' },
  { id: 'skill_axelar', slug: 'axelar', name: 'Axelar', description: 'Cross-chain communication.' },

  // Security tools
  { id: 'skill_semgrep', slug: 'semgrep', name: 'Semgrep', description: 'Static analysis tool.' },
  { id: 'skill_aws_security', slug: 'aws-security', name: 'AWS Security', description: 'AWS security services.' },
  { id: 'skill_opa', slug: 'opa', name: 'Open Policy Agent', description: 'Policy-based control.' },
  { id: 'skill_falco', slug: 'falco', name: 'Falco', description: 'Runtime security monitoring.' },
  { id: 'skill_trivy', slug: 'trivy', name: 'Trivy', description: 'Vulnerability scanner.' },
  { id: 'skill_saml', slug: 'saml', name: 'SAML', description: 'Security Assertion Markup Language.' },
  { id: 'skill_cobalt_strike', slug: 'cobalt-strike', name: 'Cobalt Strike', description: 'Adversary simulation.' },

  // Testing tools
  { id: 'skill_allure', slug: 'allure', name: 'Allure', description: 'Test report framework.' },
  { id: 'skill_percy', slug: 'percy', name: 'Percy', description: 'Visual testing platform.' },
  { id: 'skill_xcuitest', slug: 'xcuitest', name: 'XCUITest', description: 'iOS UI testing framework.' },
  { id: 'skill_espresso', slug: 'espresso', name: 'Espresso', description: 'Android UI testing.' },
  { id: 'skill_newman', slug: 'newman', name: 'Newman', description: 'Postman CLI runner.' },
  { id: 'skill_karate', slug: 'karate', name: 'Karate', description: 'API test automation.' },
  { id: 'skill_rest_assured', slug: 'rest-assured', name: 'REST Assured', description: 'Java REST API testing.' },
  { id: 'skill_pact', slug: 'pact', name: 'Pact', description: 'Contract testing framework.' },
]
